#server:
#  port: 8091

server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:moehu.net.pfx
    key-store-password: 7zU08vUL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moehu?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Lb714500.
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

logging:
  file:
    name: /root/run.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
api:
  path:
    app: app
    admin: admin
