server:
  port: 8090

#server:
#  port: 443
#  ssl:
#    enabled: true
#    key-store: classpath:moehu.net.pfx
#    key-store-password: 7zU08vUL

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dzgw?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

logging:
  file:
    name: logs/run.log

api:
  path:
    app: app
    admin: admin
